permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: Magno Macedo
description: "Tecnologia, café e devaneio"
email: magno_macedo2099@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "https://github.com/magnoDev"
repository: "https://github.com/magnoDev/magnodev.github.io"
disqus_shortname: "magno_macedo_de_oliveira"
google_analytics: 133013039

# social footer
social:
  github:
    slug: github
    link: https://github.com/magnoDev
  facebook:
    slug: facebook
    link: https://www.facebook.com/magno.macedo2099
  twitter:
    slug: twitter
    link: https://twitter.com/Magno_Macedo89
  instagram:
    slug: instagram
    link: https://www.instagram.com/magno2k99
  linkedin:
    slug: linkedin
    link: https://www.linkedin.com/in/magno-oliveira89/